# Generated by Django 3.1.7 on 2021-08-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(max_length=50)),
                ('str_code', models.CharField(max_length=5)),
                ('int_status', models.IntegerField(choices=[(0, 0), (1, 1)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(choices=[('new', 'new'), ('developed', 'developed'), ('tested', 'tested'), ('deployed', 'deployed')], max_length=50)),
                ('str_code', models.CharField(max_length=50)),
                ('int_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(max_length=50)),
                ('int_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_title', models.CharField(max_length=300)),
                ('txt_descrption', models.TextField()),
                ('jsn_attachment', models.JSONField(blank=True, null=True)),
                ('dbl_estimatation', models.FloatField(blank=True, null=True)),
                ('dat_start', models.DateField(blank=True, null=True)),
                ('dat_end', models.DateField(blank=True, null=True)),
                ('dat_created', models.DateField(auto_now=True)),
                ('dat_approved', models.DateTimeField(blank=True, null=True)),
                ('dbl_taken', models.FloatField(default=0)),
                ('int_active', models.IntegerField(default=0)),
                ('fk_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.project')),
                ('fk_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.worktype')),
                ('fk_work_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.workstatus')),
            ],
        ),
    ]
